export const medic = {
    hoverColor:"#17FD05",
    normalColor: "#12C004",
    beneathCarouselColor:"#E9FAD0",
    carousel: [
        {image:"https://wallpapercave.com/wp/wp1886330.jpg", title: "Make Profit all the way", description:"make your profit from the point of the planting to the point of sale", linkText:"Let us show you how"},
        {image:"http://6iee.com/data/uploads/12/788930.jpg", title: "Cattle lesser than 80k", description:"Get your healthy Medically tested cattles at the cheapest price, with lots of discount", linkText:"Check it out"},
        {image:"https://cms.qz.com/wp-content/uploads/2017/12/kano-farm-market.jpg", title: "Fresh Tomatoes with no preservatives", description:"Get your Fresh tomatoes at an affordable price, with discount on importation", linkText:"View more"},
        {image:"https://healthylittlepeach.com/wp-content/uploads/2018/11/DSC_0510-Copy.jpg", title: "Get all your chicken Salad Ingredients", description:"Get all your chicken Salad Ingredients at a discounted price with a free gift", linkText:"Let us show you how"},
        {image:"https://images2.alphacoders.com/560/thumb-1920-560500.jpg", title: "Want An Hour Old Bread", description:"Need the freshest bread delivered to your house within some minutes of request", linkText:"Click here"},
    ],
    beneathCarousel: [
        {bgColor:"#E9FAD0", title:"I want to become a Merchant", description:"Learn how to market your produce in the platform", image:"https://www.pngkey.com/png/full/270-2700122_business-growth-chart-icon-graph-icon-3d.png"},
        {bgColor:"#FAD0D9", title:"Buy/Sell Livestocks", description:"Register to start selling Livestocks like Goats, sheep, cattle etc", image:"http://www.pngall.com/wp-content/uploads/2016/03/Fruit-PNG-HD.png"},
        {bgColor:"#FAF9D0", title:"Wanna Become a Vegetarian", description:"We have Nutritionists online to help you out", image:"http://www.pngall.com/wp-content/uploads/2016/03/Fruit-PNG-HD.png"},
    ],
    products: [
        {name:"chicken salad", image:"http://clipart-library.com/img/2071475.png", previousPrice:2000, currentPrice:1000, new:true,  category: 1, description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis" },
        {name:"tomatoes", image:"http://clipart-library.com/img/2071475.png", previousPrice:2000, currentPrice:1000, new:true,  category: 2, description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis" },
        {name:"chicken salad", image:"http://clipart-library.com/img/2071475.png", previousPrice:2000, currentPrice:1000, new:true,  category: 3, description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis" },
        {name:"chicken salad", image:"http://clipart-library.com/img/2071475.png", previousPrice:2000, currentPrice:1000, new:false,  category: 4, description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis" },
        {name:"chicken salad", image:"http://clipart-library.com/img/2071475.png", previousPrice:2000, currentPrice:1000, new:true,  category: 5, description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis" },
        {name:"chicken salad", image:"http://clipart-library.com/img/2071475.png", previousPrice:2000, currentPrice:1000, new:false,  category: 1, description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis" },
        {name:"chicken salad", image:"http://clipart-library.com/img/2071475.png", previousPrice:2000, currentPrice:1000, new:true,  category: 2, description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis" },
        {name:"chicken salad", image:"http://clipart-library.com/img/2071475.png", previousPrice:2000, currentPrice:1000, new:true,  category: 3, description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis" },
        {name:"chicken salad", image:"http://clipart-library.com/img/2071475.png", previousPrice:2000, currentPrice:1000, new:false,  category: 4, description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis" },
        {name:"chicken salad", image:"http://clipart-library.com/img/2071475.png", previousPrice:2000, currentPrice:1000, new:true,  category: 5, description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis" },
        {name:"chicken salad", image:"http://clipart-library.com/img/2071475.png", previousPrice:2000, currentPrice:1000, new:true,  category: 1, description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis" },
        {name:"chicken salad", image:"http://clipart-library.com/img/2071475.png", previousPrice:2000, currentPrice:1000, new:false,  category: 2, description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis" }
    ],
    merchant_of_the_week: [
        {image:"https://i.pinimg.com/originals/1f/cd/b9/1fcdb91ab0415a6b385f6c8789341999.jpg", name:"David Hammed"},
        {image:"https://i.pinimg.com/originals/db/28/b8/db28b8b825931035869f103d99c98ee6.jpg", name:"Theoderic Onipe"},
        {image:"https://static.boredpanda.com/blog/wp-content/uploads/2018/10/woman-confronts-man-entering-his-building13.jpg", name:"Daniel David"},
        {image:"https://bloximages.chicago2.vip.townnews.com/stlamerican.com/content/tncms/assets/v3/editorial/f/c8/fc8248fc-bc67-11e8-9cb2-8f0ce9e20555/5ba2e32b7a8a4.image.jpg", name:"David Hammed"},
        {image:"https://i.pinimg.com/originals/1f/cd/b9/1fcdb91ab0415a6b385f6c8789341999.jpg", name:"Hammed Musa"},
    ]
}